# yaml 配置
version: '3'
services:
  env:
    build: .
    restart: always
    container_name: aofe
    tty: true
    ports:
      - "8080:8080"
    volumes: 
      - ./dist:/home/www
      - ./nginx/conf.d/aofe.conf:/etc/nginx/conf.d/aofe.conf
      - ./nginx/log:/var/log/nginx/